apiVersion: v1
kind: Service
metadata:
  name: web-svc
  labels:
    name: web
    env: dev
spec:
  selector:
    name: web
  type: LoadBalancer
  ports:
    - port: 80
      name: http
      targetPort: 80
      protocol: TCP
