apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: web-rs
  labels:
    name: web
    env: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      name: web
  template:
    metadata:
      labels:
        name: web
        env: dev
    spec:
      containers:
        - name: myweb
          image: nginx
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
